### ISSUE TITLE
Polyfill fromEntries for older versions of Node

### ISSUE THREAD

**Issue by souporserious** [braposo/figma-transformer#18]
First, thanks for such an awesome library! I love how this simplifies communicating with Figma.

I have a use-case at work where we are locked to an older version of Node and was curious if you would be willing to add an `Object.fromEntries` polyfill? I can add it to our cli tool, but figured it could be nice for anyone else on earlier versions. I can put together a PR if this sounds good, just let me know :)

**Comment by braposo** [comment]
hey @souporserious, sure I think that's fine! I'm happy for you to contribute, really appreciate the initiative!
